# Generated by Django 4.1 on 2022-09-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='CommentPost',
            new_name='post',
        ),
    ]
