# Generated by Django 4.1 on 2022-09-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likecount_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.BigIntegerField(default='0'),
        ),
    ]
