# Generated by Django 4.1 on 2022-09-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeCount',
        ),
    ]
