# Generated by Django 4.1 on 2022-09-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_series_post_overview_post_blog_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_series',
        ),
    ]
